### ISSUE TITLE
Server crash at start : Mod Loading has failed

### ISSUE THREAD

**Issue by lebanni** [NinjaPhenix/PreciseBlockPlacing#2]
MC 1.16.4
forge-1.16.4-35.1.11.jar
preciseblockplacing-1.0.3+1.16.x.jar

[crash-2020-12-09_22.40.46-fml.txt](https://github.com/NinjaPhenix/PreciseBlockPlacing/files/5668902/crash-2020-12-09_22.40.46-fml.txt)

**Comment by NinjaPhenix** [comment]
This is a client side only mod, it's not needed on the server. In any case I'll fix this when I have free time which isn't soon.

**Comment by NinjaPhenix** [comment]
Should have been fixed for a while, if not it'll will be fixed in next release which I'll be uploading shortly.
