### ISSUE TITLE
Config not works

### ISSUE THREAD

**Issue by zanecek** [NinjaPhenix/PreciseBlockPlacing#3]
After loading the world, the configuration is set to default.

I have a problem with picking up / placing the backpack (mod Sophisticated Backpacks - shift right click) and I tried to change it to see if it would help.

**Comment by zanecek** [comment]
Forge 1.16.5, sorry.

**Comment by NinjaPhenix** [comment]
Well looks like I've messed up, don't seem to be reading the values from the config.
Will get a new build out within next few hours.

**Comment by NinjaPhenix** [comment]
Fixed in 1.0.6: https://www.curseforge.com/minecraft/mc-mods/preciseblockplacing/files/3230893
